# Generated by Django 2.1.11 on 2019-10-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.IntegerField(null=True)),
                ('color', models.CharField(choices=[('TP', 'The Pair'), ('TB', 'The Black'), ('TW', 'The White')], default='TP', max_length=2)),
                ('features', models.CharField(max_length=300)),
                ('warranty', models.CharField(max_length=100)),
                ('goFarther', models.CharField(max_length=100)),
                ('goFaster', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isComplete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('bike', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='topicApp.Bike')),
                ('cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='topicApp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=40)),
                ('yearPurchased', models.IntegerField(max_length=4, null=True)),
                ('quote', models.CharField(max_length=300)),
            ],
        ),
    ]
