# Generated by Django 2.1.11 on 2019-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='yearPurchased',
            field=models.IntegerField(null=True),
        ),
    ]
