# Generated by Django 2.1.11 on 2019-10-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0002_auto_20191007_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='topicApp.Bike'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='topicApp.Cart'),
        ),
    ]
