# Generated by Django 2.1.11 on 2019-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0003_auto_20191007_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(choices=[('TB', 'Black'), ('TW', 'White')], default='TB', max_length=2),
        ),
    ]
