# Generated by Django 2.1.11 on 2019-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0004_auto_20191007_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=2),
        ),
    ]
