# Generated by Django 2.1.11 on 2019-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0005_auto_20191007_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(choices=[('Black + White', 'The Pair'), ('Black', 'Black'), ('White', 'White')], max_length=2),
        ),
    ]
