# Generated by Django 2.1.11 on 2019-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0010_bike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.CharField(default='https://1ycbx02rgnsa1i87hd1i7v1r-wpengine.netdna-ssl.com/wp-content/uploads/2017/08/EdisonBicycles_byGL-91-e1503524971119.jpg', max_length=500),
        ),
    ]
