# Generated by Django 2.1.11 on 2019-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0012_auto_20191008_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='color',
        ),
        migrations.AddField(
            model_name='bike',
            name='subtitle',
            field=models.CharField(default='Born in ATL', max_length=100),
        ),
    ]
