# Generated by Django 2.1.11 on 2019-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0013_auto_20191008_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
