# Generated by Django 2.1.11 on 2019-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0014_auto_20191008_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='subtitle',
            new_name='sub',
        ),
    ]
