# Generated by Django 2.1.11 on 2019-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0016_auto_20191008_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='sub',
        ),
    ]
