# Generated by Django 2.1.11 on 2019-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0017_remove_bike_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='subtitle',
            field=models.CharField(default='Born in ATL', max_length=100),
        ),
    ]
