# Generated by Django 2.1.11 on 2019-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0019_auto_20191008_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.CharField(choices=[('Black + White', 'The Pair'), ('Black', 'Black'), ('White', 'White')], default='Black', max_length=2),
        ),
    ]
