# Generated by Django 2.1.11 on 2019-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0020_bike_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='weight',
            field=models.IntegerField(default=46, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='yearPurchased',
            field=models.IntegerField(default=2019, null=True),
        ),
    ]
