# Generated by Django 2.1.11 on 2019-10-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0021_auto_20191009_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='topicApp.Bike')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='bike',
        ),
        migrations.AddField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='topicApp.Order'),
        ),
    ]
