# Generated by Django 2.1.11 on 2019-10-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0023_auto_20191011_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='topicApp.Bike'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
