# Generated by Django 2.1.11 on 2019-10-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0024_auto_20191011_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='topicApp.Bike'),
        ),
    ]
