# Generated by Django 2.1.11 on 2019-10-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicApp', '0026_remove_order_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='topicApp.Bike'),
        ),
    ]
